package uk.gov.companieshouse.officer.delta.processor.deserialise;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import uk.gov.companieshouse.delta.ChsDelta;
import uk.gov.companieshouse.kafka.deserialization.AvroDeserializer;
import uk.gov.companieshouse.kafka.exceptions.DeserializationException;
import uk.gov.companieshouse.kafka.exceptions.SerializationException;
import uk.gov.companieshouse.kafka.message.Message;
import uk.gov.companieshouse.kafka.serialization.AvroSerializer;

/**
 * Deserializes kafka messages using Apache Avro. The deserializer is generated by the kafka-models
 * project using the schema from chs-kafka-schemas.
 */
@Component
public class ChsDeltaDeSerializer {
    final AvroDeserializer<ChsDelta> deserializer;
    final AvroSerializer<ChsDelta> serializer;

    @Autowired
    public ChsDeltaDeSerializer(AvroDeserializer<ChsDelta> deserializer,
            final AvroSerializer<ChsDelta> serializer) {
        this.deserializer = deserializer;
        this.serializer = serializer;
    }

    /**
     * Deserializes kafka message into a ChsDelta class
     *
     * @param kafkaMessage the message from kafka
     * @return the model populated by data from the message
     * @throws DeserializationException an exception if message didn't conform to the schema
     */
    public ChsDelta deserialize(Message kafkaMessage) throws DeserializationException {
        return deserializer.fromBinary(kafkaMessage, ChsDelta.getClassSchema());
    }

    /**
     * Serializes ChsDelta class into a sequence of bytes
     *
     * @param delta the ChsDelta
     * @return the bytes representing the data from the ChsDelta
     */
    public byte[] serialize(ChsDelta delta) throws SerializationException {
        return serializer.toBinary(delta);
    }
}
