package uk.gov.companieshouse.officer.delta.processor.deserialise;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import uk.gov.companieshouse.delta.ChsDelta;
import uk.gov.companieshouse.kafka.deserialization.AvroDeserializer;
import uk.gov.companieshouse.kafka.exceptions.DeserializationException;
import uk.gov.companieshouse.kafka.message.Message;

/**
 * Deserializes kafka messages using Apache Avro. The deserializer is generated by the kafka-models
 * project using the schema from chs-kafka-schemas.
 */
@Component
public class ChsDeltaDeserializer {
    final AvroDeserializer<ChsDelta> deserializer;

    @Autowired
    public ChsDeltaDeserializer(AvroDeserializer<ChsDelta> chsDeltaAvroDeserializer) {
        deserializer = chsDeltaAvroDeserializer;
    }

    /**
     * Deserializes kafka message into a ChsDelta class
     *
     * @param kafkaMessage the message from kafka
     * @return the model populated by data from the message
     * @throws DeserializationException an exception if message didn't conform to the schema
     */
    public ChsDelta deserialize(Message kafkaMessage) throws DeserializationException {
        return deserializer.fromBinary(kafkaMessage, ChsDelta.getClassSchema());
    }
}
